### ISSUE TITLE
"Routine" Screen

### ISSUE THREAD

**Issue by kaisenl** [UX-Wizards/CareMe#7]
We're going to build out the first iteration of the Routine screen. We want to know if we have the proper UX flows, so let's focus on getting the visual layout done, and not worry about getting the exact styling correct since that may change later anyway. When thinking about the layout, pay attention to the:
- Typeface
- Alignment
- Margins and Padding
- Grid

Here are some ionic components to look into:
- https://ionicframework.com/docs/api/grid
- https://ionicframework.com/docs/api/nav
- https://ionicframework.com/docs/api/toggle
- https://ionicframework.com/docs/api/text
- https://ionicframework.com/docs/api/icon

It's more important at this point that you get some experience using Ionic components rather than focusing on a pixel perfect implementation of the design.

**Reference Design Image**
![image](https://user-images.githubusercontent.com/520254/225835184-74761ab9-4b10-4738-9d76-5fcc2d2c4190.png)

**Comment by dginelsa** [comment]
Instead of toggle, this component can possibly be used as well:
https://ionicframework.com/docs/api/segment

**Comment by justinajong** [comment]
Hello @kaisenl @mingshi0821 

Let's use the design from the V2 

[Routine - 1.pdf](https://github.com/UX-Wizards/CareMe/files/11057482/Routine.-.1.pdf)
[Routine - 2.pdf](https://github.com/UX-Wizards/CareMe/files/11057483/Routine.-.2.pdf)
